import { CareerProps } from '../types/careers';

export const CAREERS: CareerProps[] = [
  {
    position: 'Senior Frontend Developer',
    company: 'XIOTS',
    company_legal_name: 'XIOTS',
    logo: '/images/careers/xiots.svg',
    location: 'Blackburn Suite 1M Number One The beehive Lions Drive',
    location_type: 'Hybrid',
    type: 'Full-time',
    start_date: '2020-10',
    end_date: null,
    industry: 'software',
    link: '#',
    responsibilities: [
      'Leading frontend development efforts, crafting high-performance, scalable, and user-focused applications.',
      'Managing and mentoring a team of frontend developers, ensuring best practices in coding standards, performance, and design.',
      'Skilled in advanced JavaScript frameworks and libraries, including React, Next.js, and Tailwind CSS.',
      'Overseeing project timelines and ensuring successful delivery of frontend features.',
      'Prioritizing user experience through responsive, intuitive, and visually engaging interfaces.',
      'Working closely with cross-functional teams to align frontend goals with overall business objectives.',
    ],
  },
  {
    position: 'Junior React Native Developer',
    company: 'Digit Solutions',
    company_legal_name: 'Digit Solutions (Private) Limited',
    logo: '/images/careers/digitSol.jpeg',
    location: 'F8 Islamabad, Pakistan',
    location_type: 'On-site',
    type: 'Full-time',
    start_date: '2021-02',
    end_date: '2022-01',
    industry: 'software',
    link: '#',
    responsibilities: [
      'Developed mobile applications using React Native and TypeScript for Android and iOS platforms.',
      'Built reusable UI components and implemented smooth navigation and responsive layouts.',
      'Integrated REST APIs, handled authentication using JWT, and managed app state with Context API / Redux Toolkit.',
      'Implemented form validation, error handling, and loading states to enhance user experience.',
      'Optimized performance using efficient list rendering and component re-render management.',
    ],
  },
];
